#!/bin/bash

mapfile -t compliments < words.txt

work=1
break=1

# get random compliments
function get_rand_compliments(){
    my_random=$((1 + RANDOM % 104))
    compliment=${compliments[my_random]}
}

function work_end(){
    if [ $work = 4 ]; then
        aplay ~/sounds/early-sunrise-yey.wav &
        # reset time
        $work=0
        $break=0
    else
        aplay ~/sounds/wind-chime-rest.wav &
    fi
    #zenity --warning --text="break time \n You work $work times"
    yad --title "Break Time" --warning --text "<b>$compliment</b> \n Have a nice break." --width=300 --center --button="gtk-cancel:252" --button="gtk-ok:0"
    let work++
}

function break_end(){
    aplay ~/sounds/sparkle-work.wav &
    yad --title "Work Time" --warning --text=" <b>$compliment</b> \n Back to work."
    let break++
}

function countdown(){
    date1=$((`date +%s` + $1));
    while [ "$date1" -ge `date +%s` ]; do
        echo -ne "$(date -u --date @$(($date1 - `date +%s`)) +%H:%M:%S)\r";
        sleep 0.1
    done
}

while :
do
    echo "Press [CTRL+C] to stop."
    echo "Yes you can!"

    # work
    sleep 1500 & \
        if [ $work = 1 ]; then
            echo "You work $work time"
        else
            echo "You work $work times"
        fi
        countdown 1500 # 25 minutes work
        get_rand_compliments
        work_end

        # break
        if [ $work = 4 ]; then
            sleep 1800 & countdown 1800 # 30 minutes break
        else
            sleep 300 & countdown 300 # 5 minutes break
        fi
        get_rand_compliments
        break_end
done
